# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6df51aa4bc8f380f1bf9a77f3a01f3d89812b9d8d767c8eb1fbc61a2688eac0a678fb34bda8255391460af3b9dfdd615dd0645d49fa846a2b7c3f5d04b2b84f4

test:
  secret_key_base: a490522701449ef10336c6fca758cab36a531086296168e1736992fc983a612ad5ac3fec401a6801039852992a4014bc40bc1aa5f9bb50d29b8f31d6bf83258e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
